GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/63f88510c88625615e0d0e90

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jeezus",
  "number": "333"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "prova1",
  "number": "123-4567890"
}

###
DELETE http://localhost:3001/api/persons/63f89698b66bfd57ad7eb9ac

###
PUT http://localhost:3001/api/persons/63f89231273d14875be238a0
Content-Type: application/json

{
  "name": "IVA"
}

###
PUT http://localhost:3001/api/persons/63f879a544f887a4691907e3
Content-Type: application/json

{
  "number": "3-12345"
}



###
### Deployed application 
###

###
GET https://phonebook-rest-api.onrender.com/api/persons

###
POST https://phonebook-rest-api.onrender.com/api/persons
Content-Type: application/json

{
  "name": "ehehehe",
  "number": "666"
}

###
POST https://phonebook-rest-api.onrender.com/api/persons
Content-Type: application/json

{
  "name": "Jeezus"
}

###
DELETE https://phonebook-rest-api.onrender.com/api/persons/5

