GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/63f88510c88625615e0d0e90

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jeezus",
  "number": "333"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arara",
  "number": "2"
}

###
DELETE http://localhost:3001/api/persons/63f885ef0135d1f3562e8e70

###
PUT http://localhost:3001/api/persons/63f885ef0135d1f3562e8e71
Content-Type: application/json

{
  "number": "IVA"
}

###
PUT http://localhost:3001/api/persons/63f879a544f887a4691907e3
Content-Type: application/json

{
  "number": "3-12345"
}



###
### Deployed application 
###

###
GET https://phonebook-rest-api.onrender.com/api/persons

###
POST https://phonebook-rest-api.onrender.com/api/persons
Content-Type: application/json

{
  "name": "Jeezus",
  "number": "666"
}

###
POST https://phonebook-rest-api.onrender.com/api/persons
Content-Type: application/json

{
  "name": "Jeezus"
}

###
DELETE https://phonebook-rest-api.onrender.com/api/persons/5

